### PR TITLE
Translate menu list on admin page

### PR DESCRIPTION
**Pull request by camelmasa**
I translated translated menu list on admin page.

### CODE REVIEW

**Comment by tvdeyen** [comment]
Thank you very much. Please update your commit message to something like:

```
Translates some Japanese words.
```

We want to see which language was translated in each commit at a glance, without having to look into each commits diff.

Thank you again for your contribution and your understanding in clean, meaningful commit messages.

**Comment by tvdeyen** [comment]
@camelmasa could you please rebase with `master`. Should fix the build problems. Thanks

**Comment by camelmasa** [comment]
@tvdeyen Thank you for reply. Please merge it if possible.

**Comment by tvdeyen** [comment]
@camelmasa will do after you changed the commit message to something [like I proposed above](https://github.com/solidusio-contrib/solidus_i18n/pull/8#issuecomment-172315079). 

Read more about the importance of commit messages in this post: http://chris.beams.io/posts/git-commit/

Thanks for your understanding.

**Comment by camelmasa** [comment]
@tvdeyen I reworded the commit message to "Translate menu list on admin page" but I couldn't write commit message better. sorry, I'll close it.

**Comment by tvdeyen** [comment]
@camelmasa please understand, that it is important for us to have the language in the commit message. Consider to read the git log and see a lot of "fix translations" commits. It will be very helpful for us to have the language that was translated to be in the commit message.

It is very easy to rewrite a commit message with git.

In your case:

```
git checkout translate
git commit --amend -m 'Translate menu list on admin page into Japanese.'
git push -f
```

Thanks

**Pull request closed without merging**
