### PR TITLE
Translation and modification of some words in Slovak language

### PR DESCRIPTION
**Pull request by modreoci**

### CODE REVIEW

**Comment by tvdeyen** [comment]
Please change your commit message so we see

**Comment by modreoci** [comment]
I'm newbie on github... What kind of change do you mean?
Dňa 20.1.2016 12:30 AM používateľ "Thomas von Deyen" <
notifications@github.com> napísal:

**Comment by modreoci** [comment]
Sorry... Your message was shortened in gmail... Now it is clear...

**Comment by tvdeyen** [comment]
Thanks. But I didn't meant the pull request title (that's also great), I meant the commit itself. 

Image running `git log` in you terminal and see lots of "updated some translation" commits. We would like to see which language was update at a glance. 

So please `git commit --amend` alter the message and `git push -f` your branch. 

Thank you again for your contribution

**Comment by modreoci** [comment]
Mhmmm... :-) I did it by web interface, not from my machine (I have not pulled it locally)... Is there a way to correct it by web UI?

**Comment by modreoci** [comment]
I cloned it to my machine and fired git commit --amend as you recommended but it appears something like this:

Merge pull request #4 from dpsk/patch-1

Update ru.yml

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Thomas von Deyen <tvd@bitspire.de>
#
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#       modified:   config/locales/ru.yml
#

What now? :-O

**Comment by tvdeyen** [comment]
You need to checkout your branch to see your commit:

`git checkout patch-1`

**Comment by modreoci** [comment]
Well... How simple :-D

**Comment by tvdeyen** [comment]
Thank you very much. 

BTW: There some great git tutorials out there

* https://try.github.io
* http://pcottle.github.io/learnGitBranching/

**Comment by modreoci** [comment]
Yesss... It works!... Done... Thanks for advice ;-) I'm little bit more clever again :-)

**Comment by modreoci** [comment]
What if I'll want to go on in translation. Can I continue to edit the same file on this branch (patch-1) and commit it again from it or I have to create the new one? Sorry for probably stupid questions, but as I said - I'm completly newbie... :-/

**Comment by tvdeyen** [comment]
You can continue to work and push into this branch until you are finished. Just gives us an update, when you're done.

**Comment by modreoci** [comment]
I pushed new commit to my patch-1 branch. What is necessary to do next?

**Comment by tvdeyen** [comment]
Nothing unless you are ready and say we can merge this in. Thanks

**Comment by modreoci** [comment]
In the last commit there is huge amount of translated terms but it is still not end of the work on it. Is it sensible to merge it partially after some amount of work?

**Comment by modreoci** [comment]
Please merge it!
It remains only a few terms untranslated. Some of them I didn't understand so I'll translate them when I'll see them in real usage.

**Comment by tvdeyen** [comment]
Thanks, please [quash the three commits into one](https://davidwalsh.name/squash-commits-git), then I can merge this.

**Comment by modreoci** [comment]
It is already sqashed... ;-)

**Comment by tvdeyen** [comment]
Sorry, for the delay!

**Pull request merged**
