### PR TITLE
Switch to I18n::Backend::Simple.new due to i18n-js compatibility

### PR DESCRIPTION
**Pull request by kennyadsl**
This will fix https://github.com/fnando/i18n-js/issues/344

### CODE REVIEW

**Comment by kennyadsl** [comment]
👍 We can probably revert this whole commit: https://github.com/solidusio-contrib/solidus_i18n/commit/1bec159f2586186608dda00c0bbb243f2c4f1c05. I think `i18n_data` would be useless as well.

**Comment by jhawthorn** [comment]
I think unfortunately this is being used by [BaseHelper's `available_countries`](https://github.com/solidusio/solidus/blob/master/core/app/helpers/spree/base_helper.rb#L117)

**Comment by jhawthorn** [comment]
Amusingly, this doesn't check the scope of the translation:

```
I18n.t('CA', scope: 'foo.bar.baz') #=> "Canada"
```

**Comment by jhawthorn** [comment]
#2537 solves this and is ready to go, but I'm not sure how to handle this version-wise.

If we remove this initializer we'll be dropping support for translating countries in all versions < 2.5. Maybe we need a major version bump, to make this `solidus_i18n` `2.0`.

**Comment by kennyadsl** [comment]
I've prepared a PR (#108) to remove this dependency if we go for the major version bump. 

Alternatively we could leave the initializer and conditionally load that code only for some solidus version using [this check](https://github.com/solidusio/solidus_support/blob/master/lib/solidus_support.rb#L7)?

**Comment by jhawthorn** [comment]
Solved by #122 :tada:

**Pull request closed without merging**
