### PR TITLE
Add lot of French translations

### PR DESCRIPTION
**Pull request by damienlethiec**
I added a lot of the French missing translations.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Merci beaucoup.

Unfortunately, this seems not parse as valid YAML. It's confusing; it looks fine to me.

>  did not find expected key while parsing a block mapping at line 691 column 7

**Comment by damienlethiec** [comment]
Looks fine to me too ^^

**Comment by jhawthorn** [comment]
There were a few issues. Here's what I needed to change https://github.com/jhawthorn/solidus_i18n/commit/9eca053f3872103e9bd6edd715431f95b71de521

**Comment by jhawthorn** [comment]
Merged as cf3c7080ff2d6583c090c839a0b856f2ff9e44ae :tada:

**Comment by damienlethiec** [comment]
Thanks a ton !!

**Pull request closed without merging**
