### PR TITLE
Explicitly use full constant name in locale helper

### LINKED ISSUE #73: SolidusI18n error with solidus v2.0.0
I see forrowing error at Admin-Settings with solidus v2.0.0.
when I remove a line "gem 'solidus_i18n'" from Gemfile, I don't see this error.

```
NameError in Spree::Admin::GeneralSettings#edit

Showing /var/www/solidus/backend/app/views/spree/admin/general_settings/edit.html.erb where line #71 raised:

uninitialized constant SolidusI18n::LocaleHelper::Locale

Extracted source (around line #18):
16 # this project. solidusio/solidus now has those keys.
17 def all_locales_options
18 Locale.all.map { |locale| locale_presentation(locale) }.push(['English (EN)', :en])
19 end
20
21 private
```

### PR DESCRIPTION
**Pull request by tvdeyen**
Sometimes Rails Module lockup causes errors like in https://github.com/solidusio-contrib/solidus_i18n/issues/73

Closes #73

### CODE REVIEW

**Comment by fschwahn** [comment]
@tvdeyen rails autoloading usually (or by default) does not include the lib directory, only stuff in `app` is autoloaded. I think the better way to fix this would be to just require this file in `lib/solidus_i18n.rb`.

**Comment by tvdeyen** [comment]
@fschwahn good catch! Will do. Thanks for the heads up

**Comment by fschwahn** [comment]
@tvdeyen @mamhoff you can reproduce this issue by putting `config.cache_classes = true` and `config.eager_load = true` (ie. disable autoloading) and visiting "/en/admin/general_settings/edit".

**Comment by mamhoff** [comment]
@fschwahn If you tell me it fixes your issue, I'll trust you on it.

**Comment by fschwahn** [comment]
Yes, this fixes the issue, but the change to `LocaleHelper` is not necessary, just the require.

**Comment by tvdeyen** [comment]
> but the change to LocaleHelper is not necessary

I know, but it is not harmful and even better to avoid strange Rails module namespace lookup issues like in https://github.com/solidusio/solidus/pull/1615

**Comment by fschwahn** [comment]
Yes, you're right

**Pull request merged**
